[versions]

kotlin = "2.1.21"
compose = "1.9.3"
material3 = "1.9.0-alpha04"
agp = "8.10.0"
androidx-activityCompose = "1.10.1"
androidx-uiTest = "1.8.1"
kermit = "2.0.6"
kotlinx-coroutines = "1.10.2"
androidx-lifecycle = "2.9.1"
androidx-navigation = "2.9.0-beta03"
androidx-graphics-shapes = "1.0.1"
kotlinx-datetime = "0.7.1-0.6.x-compat"
buildConfig = "5.6.5"
room = "2.7.2"
sqlite = "2.5.0-alpha01"
koin-bom = "4.0.3"
ksp = "2.1.21-2.0.2"
runner = "1.6.2"
kotlinx-serialization = "1.7.3"
turbine = "1.2.1"
juint = "4.13.2"
coil = "3.3.0"
ktor = "3.3.3"
koog= "0.6.2"
[libraries]

androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-uitest-testManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-uiTest" }
androidx-graphics-shapes = {module = "androidx.graphics:graphics-shapes", version.ref = "androidx-graphics-shapes" }
androidx-uitest-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-uiTest" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kermit-koin = { module = "co.touchlab:kermit-koin", version.ref = "kermit" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-compose-viewmodel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
turbine = {module = "app.cash.turbine:turbine",version.ref = "turbine"}
junit = { module = "junit:junit", version.ref = "juint" }
#back-handler = {module = "org.jetbrains.compose.ui:ui-backhandler" }
coil = {module = "io.coil-kt.coil3:coil-compose",version.ref="coil"}
coil-svg = {module = "io.coil-kt.coil3:coil-svg",version.ref="coil"}
ktor-core = {module = "io.ktor:ktor-client-core",version.ref="ktor"}
ktor-cio = {module = "io.ktor:ktor-client-cio",version.ref="ktor"}
# Theme
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }

[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "agp" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig" }
room = { id = "androidx.room", version.ref = "room" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }